# Generated by Django 5.0.2 on 2025-05-06 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixit_frw', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ['created']},
        ),
    ]
