# Generated by Django 5.0.2 on 2025-06-30 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixit_frw', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='address',
        ),
        migrations.AlterModelTable(
            name='payments',
            table='payments',
        ),
    ]
