# Generated by Django 5.0.2 on 2025-06-30 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixit_frw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='fixit_frw.address'),
        ),
    ]
