# Generated by Django 5.0.2 on 2025-05-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixit_frw', '0002_alter_items_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='category',
            field=models.TextField(choices=[('HOUSE_APPLIANCES', 'House Appliances'), ('ELECTRONIC', 'Electronic'), ('OTHER', 'Other')], default='OTHER'),
        ),
    ]
