# Generated by Django 5.0.2 on 2025-07-18 04:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixit_frw', '0003_alter_address_city_alter_address_province_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payments',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payments',
            name='method',
            field=models.CharField(choices=[('GOPAY', 'Gopay'), ('TRANSFER', 'Transfer'), ('COD', 'Cod')], default='COD'),
        ),
    ]
