# Generated by Django 5.0.2 on 2025-07-24 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixit_frw', '0004_payments_amount_payments_date_payments_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fixit_frw.payments'),
        ),
    ]
