# Generated by Django 5.0.2 on 2025-07-25 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixit_frw', '0005_items_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='address_id',
        ),
    ]
