# Generated by Django 5.0.2 on 2025-07-25 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixit_frw', '0006_remove_items_address_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address_id',
            new_name='address',
        ),
    ]
