# Generated by Django 5.0.2 on 2025-07-25 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixit_frw', '0007_rename_address_id_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fixit_frw.address'),
        ),
    ]
